apiVersion: v1
kind: PersistentVolume
metadata:
  name: hangout-auth-service-pv
  labels:
    type: local-storage
    app: hangout-auth-service
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /usr/src/app/logs