apiVersion: apps/v1
kind: Deployment
metadata:
  name: hangout-auth-service-deployment
  labels:
    type: core-services
    role: authentication-and-authorization
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hangout-auth-service
  template:
    metadata:
      labels:
        app: hangout-auth-service
    spec:
      containers:  
      - name: hangout-auth-service
        image: opticsquid/hangout-auth-service:1.1.0
        ports:
          - containerPort: 5011
        envFrom:
          - secretRef:
              name: hangout-auth-service-secret
          - configMapRef:
              name: hangout-auth-service-configmap
        volumeMounts:
        - name: hangout-auth-service-logs
          mountPath: /usr/src/app/logs
      volumes:
      - name: hangout-auth-service-logs
        persistentVolumeClaim:
          claimName: hangout-auth-service-pvc