apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: persistance
  labels:
    type: local-storage
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/postgresql