receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317
  hostmetrics:
    collection_interval: 10s
    scrapers:
      # CPU utilization metrics
      cpu:
      # Disk I/O metrics
      disk:
      # File System utilization metrics
      filesystem:
      # CPU load metrics
      load:
        cpu_average: true
      # Memory utilization metrics
      memory:
      # Network interface I/O metrics & TCP connection metrics
      network:
      # Paging/Swap space utilization and I/O metrics
      paging:

processors:
  batch:
  resourcedetection:
    detectors: [env, system]
  cumulativetodelta:

exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: 0.0.0.0:8889
    const_labels:
      origin: otel-collector
  # this is tempo
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  otlphttp/loki:
    endpoint: "http://loki:3100/otlp"

extensions:
  health_check:
  pprof:
  zpages:

service:
  pipelines:
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [cumulativetodelta, batch, resourcedetection]
      # exporters: [prometheus, debug]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      # exporters: [zipkin, otlp/jaeger, otlp, debug]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      exporters: [otlphttp/loki]
  telemetry:
    metrics:
      level: detailed
      readers:
        - pull:
            exporter:
              prometheus:
                host: "0.0.0.0"
                port: 8888
