receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: 0.0.0.0:8889
    const_labels:
      origin: otel-collector
  # this is tempo
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      # exporters: [prometheus, debug]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      # exporters: [zipkin, otlp/jaeger, otlp, debug]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      exporters: [loki]
