apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
        - name: hangout-auth-api
          image: ghcr.io/opticsquid/hangout-auth-api:v2.1.0
          ports:
            - containerPort: 5011
              name: main
              protocol: TCP
          envFrom:
            - secretRef:
                name: hangout-auth-service-secret
            - configMapRef:
                name: hangout-auth-service-configmap
          volumeMounts:
            - name: auth-api-logs
              mountPath: /logs
      volumes:
        - name: auth-api-logs
          persistentVolumeClaim:
            claimName: auth-api
