apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-api
  labels:
    app: auth-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
