apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hangout-auth-service-pvc
  labels:
    type: full-claim
    app: hangout-auth-service
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi