yamlApplicationConfig:
  kafka:
    clusters:
      - name: local
        bootstrapServers:  kafka.persistance:9092
  auth:
    type: disabled
  management:
    health:
      ldap:
        enabled: false