server:
    http_listen_port: 3200

distributor:
    receivers:
        otlp:
            protocols:
                http:
                grpc:
                  endpoint: 0.0.0.0:4316

# ingester:
#   max_block_duration: 5m

# compactor:
#     compaction:
#         block_retention: 1h

metrics_generator:
    registry:
        external_labels:
            source: tempo
            cluster: docker-compose
    storage:
        path: /tmp/tempo/generator/wal
        remote_write:
            - url: http://prometheus:9090/api/v1/write
              send_exemplars: true
    traces_storage:
        path: /var/tempo/generator/traces

storage:
    trace:
        backend: local                     # backend configuration to use
        wal:
            path: /tmp/tempo/wal             # where to store the wal locally
        local:
            path: /tmp/tempo/blocks

overrides:
    defaults:
        metrics_generator:
            # enables metrics generator
            processors: 
              - service-graphs
              - span-metrics
              - local-blocks 
            generate_native_histograms: both
