apiVersion: v1
kind: Service
metadata:
  name: hangout-notification-service
  labels:
    app: hangout-notification-service
spec:
  type: ClusterIP
  ports:
    - port: 5012
  selector:
    app: hangout-notification-service