apiVersion: apps/v1
kind: Deployment
metadata:
  name: hangout-notification-service-deployment
  labels:
    type: core-services
    role: alerts-and-notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hangout-notification-service
  template:
    metadata:
      labels:
        app: hangout-notification-service
    spec:
      containers:  
      - name: hangout-notification-service
        image: opticsquid/hangout-notification-service:v1.0.1
        ports:
          - containerPort: 5012
            protocol: TCP
        envFrom:
          - secretRef:
              name: hangout-notification-service-secret
          - configMapRef:
              name: hangout-notification-service-configmap