apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: persistance
  labels:
    app: minio
type: Opaque
data:
  # ROOTUSER
  MINIO_ROOT_USER: Uk9PVFVTRVI=
  # CHANGEME123
  MINIO_ROOT_PASSWORD: Q0hBTkdFTUUxMjM=
