apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config-map
  namespace: persistance
data:
  MINIO_PROMETHEUS_URL: http://hangout-prometheus-1:9090
  MINIO_AUDIT_KAFKA_ENABLE: "on"
  MINIO_AUDIT_KAFKA_BROKERS: hangout-kafka-1:19091
  MINIO_AUDIT_KAFKA_TOPIC: minio-audit-logs
