apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: persistance
  labels:
    app: minio
spec:
  selector:
    app: minio
  type: ClusterIP
  ports:
    - port: 9000
      name: api
    - port: 9001
      name: console
