global:
  scrape_interval: 60s
  evaluation_interval: 90s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: "otel-collector"
    static_configs:
      - targets:
          - otel-collector:8889

  - job_name: "kafka"
    static_configs:
      - targets:
          - kafka:9095 # Target Kafka's metrics endpoint
