global:
  scrape_interval: 60s
  evaluation_interval: 90s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: "open telemetry exported metrics"
    static_configs:
      - targets:
          - otel-collector:8889

  - job_name: "open telemetry collector metrics"
    static_configs:
      - targets:
          - otel-collector:8888

  - job_name: "container metrics"
    static_configs:
      - targets:
          - cadvisor:8080
