global:
  scrape_interval: 60s
  evaluation_interval: 90s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["host.docker.internal:9090"]

  - job_name: 'otel-collector'
    static_configs:
      - targets: 
        - hangout-otel-collector-1:8889
        
  - job_name: hangout-storage-service
    metrics_path: /q/metrics
    static_configs:
      - targets: ["host.docker.internal:9000"]
    # scrape_interval: 30s
