global:
  scrape_interval: 60s
  evaluation_interval: 90s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: "otel-collector"
    static_configs:
      - targets:
          - otel-collector:8889

  - job_name: minio-job
    bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoiM0Z5a0REOHpaSFB4OHVLZ1BiQmYiLCJleHAiOjQ4OTAzNjUyNDd9.KR5rfkLKNH4vh7cARHxb_hMQTLJBFXVQaZouDCIMrSMzwknFYB-YPeoHyvFCln0gTZOZkJR8ynTzYfGO-vjxuA
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
      - targets:
          - minio:9000
