global:
  scrape_interval: 60s
  evaluation_interval: 90s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: "otel-collector"
    static_configs:
      - targets:
          - otel-collector:8889

  - job_name: "minio-job"
    bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoiNkNZZHpzRW5XU2l4VWR5a2lBYVQiLCJleHAiOjQ4OTQ4MzU1NDV9.KFlS4HDSTKerh9YarXuvBdfwBLbK-kK0zln6sG10w1bcwpfGzSfyDPN0RENzuSbD3gsI5rqCi8bReNLxNRWXOQ
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
      - targets:
          - host.docker.internal:9000
