global:
    scrape_interval: 60s
    evaluation_interval: 90s

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['host.docker.internal:9090']
    - job_name: eureka-discovery
      metrics_path: /actuator/prometheus
      eureka_sd_configs:
        - server: 'http://host.docker.internal:8761/eureka'
          refresh_interval: 60s
      relabel_configs:
        - source_labels: [ __meta_eureka_app_name ]
          target_label: application
        - source_labels: [ __meta_eureka_app_instance_metadata_metrics_path ]
          target_label: metrics_path
        - source_labels: [ __address__ ]
          target_label: instance

