apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: geo-postgres-server
  namespace: layer0
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgis:17
  enableSuperuserAccess: true      
  storage:
    size: 1Gi
