apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hangout-ingress
  labels:
    app: hangout-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: hangout-auth-service
            port:
              number: 5011
