apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: persistance
spec:
  serviceName: "postgres"
  replicas: 1 # Single DB server for all pods
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgis/postgis # Your custom PostgreSQL image
          ports:
            - containerPort: 5432
              name: postgres
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi # Adjust size as needed
        storageClassName: "standard" # Minikube's default StorageClass
